services:
  mq:
    image: "mq-amazon:latest"
    ports:
      - 9443:9443
      - 1414:1414
      - 9157:9157
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=${APP_PASSWORD:?err}
      - MQ_ADMIN_PASSWORD=${ADMIN_PASSWORD:?err}
    volumes:
      - qm1data:/mnt/mqm
    networks:
      - qm1network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1Gb
volumes:
  qm1data:
    driver_opts:
      gid: 0
    labels:
      - com.ibm.mq=qm1
networks:
  qm1network:
    labels:
      - com.ibm.mq=qm1