services:
  mqm:
    image: "mq-amazon:latest"
    
    ports:
      - "1414:1414/tcp"
      - "9443:9443/tcp"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "container=oci"

    command:
      - "/sbin/init"

    ipc: "private"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "bridge"

    stdin_open: true

    tty: true

    user: "root"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1Gb

    tmpfs:
      - /tmp
      - /run

    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup"

    working_dir: "/opt/mqm/bin/"